import jsPDF from 'jspdf';
import { LoanData } from '../types/chatbot';

export const generateLoanRoadmapPDF = (
  loanData: LoanData,
  insights: string
): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPos = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Loan Repayment Roadmap', pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, pageWidth / 2, yPos, {
    align: 'center',
  });
  yPos += 15;

  // Loan Summary Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Loan Summary', 20, yPos);
  yPos += 10;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const loanDetails = [
    `Principal Amount: ₹${loanData.principal.toLocaleString('en-IN')}`,
    `Interest Rate: ${loanData.interestRate}% per annum`,
    `EMI Amount: ₹${loanData.emiAmount.toLocaleString('en-IN')}`,
    `Tenure: ${loanData.tenure} months (${Math.floor(loanData.tenure / 12)} years)`,
  ];

  if (loanData.totalInterest) {
    loanDetails.push(`Total Interest: ₹${loanData.totalInterest.toLocaleString('en-IN')}`);
  }
  if (loanData.totalAmount) {
    loanDetails.push(`Total Amount Payable: ₹${loanData.totalAmount.toLocaleString('en-IN')}`);
  }

  loanDetails.forEach((detail) => {
    doc.text(detail, 20, yPos);
    yPos += 7;
  });

  yPos += 10;

  // Repayment Schedule
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Repayment Schedule Highlights', 20, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const monthlyInterestRate = loanData.interestRate / 12 / 100;
  let remainingPrincipal = loanData.principal;

  // Show first 6 months, middle month, and last month
  const scheduleMonths = [1, 2, 3, 6, 12, Math.floor(loanData.tenure / 2), loanData.tenure];
  const uniqueMonths = [...new Set(scheduleMonths)].filter((m) => m <= loanData.tenure).sort((a, b) => a - b);

  uniqueMonths.forEach((month) => {
    // Calculate for this month
    const tempPrincipal = loanData.principal;
    let tempRemaining = tempPrincipal;

    for (let i = 1; i <= month; i++) {
      const interest = tempRemaining * monthlyInterestRate;
      const principalPaid = loanData.emiAmount - interest;
      tempRemaining -= principalPaid;
    }

    const interest = tempRemaining * monthlyInterestRate;
    const principalPaid = loanData.emiAmount - interest;

    if (yPos > pageHeight - 30) {
      doc.addPage();
      yPos = 20;
    }

    doc.text(
      `Month ${month}: EMI ₹${loanData.emiAmount.toLocaleString('en-IN')} | Principal: ₹${principalPaid.toFixed(0)} | Interest: ₹${interest.toFixed(0)} | Balance: ₹${Math.max(0, tempRemaining).toFixed(0)}`,
      20,
      yPos
    );
    yPos += 6;
  });

  yPos += 10;

  // AI Insights Section
  if (yPos > pageHeight - 60) {
    doc.addPage();
    yPos = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('AI-Generated Insights & Recommendations', 20, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  // Split insights into lines that fit the page width
  const maxWidth = pageWidth - 40;
  const insightLines = doc.splitTextToSize(insights, maxWidth);

  insightLines.forEach((line: string) => {
    if (yPos > pageHeight - 20) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(line, 20, yPos);
    yPos += 6;
  });

  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text(
      `Page ${i} of ${totalPages} | Generated by Loan Freedom AI Assistant`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  doc.save(`loan-roadmap-${new Date().toISOString().split('T')[0]}.pdf`);
};
