import { Achievement } from '../types';

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: '1',
    code: 'first_loan',
    name: 'Journey Begins',
    description: 'Added your first loan to FinLiberate',
    category: 'prepayment',
    icon: 'target',
    points: 10,
    criteria: { loansAdded: 1 },
  },
  {
    id: '2',
    code: 'first_payment',
    name: 'First Step',
    description: 'Made your first EMI payment',
    category: 'streak',
    icon: 'check-circle',
    points: 20,
    criteria: { paymentsCount: 1 },
  },
  {
    id: '3',
    code: 'first_prepayment',
    name: 'Prepayment Hero',
    description: 'Made your first extra payment',
    category: 'prepayment',
    icon: 'zap',
    points: 50,
    criteria: { extraPayments: 1 },
  },
  {
    id: '4',
    code: 'streak_3',
    name: '3 Month Warrior',
    description: 'Maintained a 3-month payment streak',
    category: 'streak',
    icon: 'flame',
    points: 30,
    criteria: { streak: 3 },
  },
  {
    id: '5',
    code: 'streak_6',
    name: '6 Month Champion',
    description: 'Maintained a 6-month payment streak',
    category: 'streak',
    icon: 'flame',
    points: 75,
    criteria: { streak: 6 },
  },
  {
    id: '6',
    code: 'streak_12',
    name: 'Year Long Master',
    description: 'Maintained a 12-month payment streak',
    category: 'streak',
    icon: 'trophy',
    points: 150,
    criteria: { streak: 12 },
  },
  {
    id: '7',
    code: 'saved_50k',
    name: 'Smart Saver',
    description: 'Saved ₹50,000 in interest',
    category: 'savings',
    icon: 'piggy-bank',
    points: 100,
    criteria: { interestSaved: 50000 },
  },
  {
    id: '8',
    code: 'saved_1l',
    name: 'Savings Expert',
    description: 'Saved ₹1,00,000 in interest',
    category: 'savings',
    icon: 'trending-up',
    points: 200,
    criteria: { interestSaved: 100000 },
  },
  {
    id: '9',
    code: 'saved_5l',
    name: 'Interest Ninja',
    description: 'Saved ₹5,00,000 in interest',
    category: 'savings',
    icon: 'award',
    points: 500,
    criteria: { interestSaved: 500000 },
  },
  {
    id: '10',
    code: 'months_saved_6',
    name: 'Time Saver',
    description: 'Accelerated loan by 6 months',
    category: 'speed',
    icon: 'clock',
    points: 80,
    criteria: { monthsSaved: 6 },
  },
  {
    id: '11',
    code: 'months_saved_12',
    name: 'Speed Runner',
    description: 'Accelerated loan by 1 year',
    category: 'speed',
    icon: 'rocket',
    points: 150,
    criteria: { monthsSaved: 12 },
  },
  {
    id: '12',
    code: 'months_saved_24',
    name: 'Freedom Fighter',
    description: 'Accelerated loan by 2 years',
    category: 'speed',
    icon: 'zap',
    points: 300,
    criteria: { monthsSaved: 24 },
  },
  {
    id: '13',
    code: 'quarter_complete',
    name: '25% Free',
    description: 'Paid off 25% of your loan',
    category: 'prepayment',
    icon: 'pie-chart',
    points: 50,
    criteria: { percentComplete: 25 },
  },
  {
    id: '14',
    code: 'half_complete',
    name: 'Halfway Hero',
    description: 'Paid off 50% of your loan',
    category: 'prepayment',
    icon: 'circle-half',
    points: 100,
    criteria: { percentComplete: 50 },
  },
  {
    id: '15',
    code: 'three_quarter_complete',
    name: '75% Champion',
    description: 'Paid off 75% of your loan',
    category: 'prepayment',
    icon: 'trending-up',
    points: 200,
    criteria: { percentComplete: 75 },
  },
  {
    id: '16',
    code: 'almost_free',
    name: 'Almost There',
    description: 'Paid off 90% of your loan',
    category: 'prepayment',
    icon: 'star',
    points: 250,
    criteria: { percentComplete: 90 },
  },
];

export const MOCK_BANKS = [
  { name: 'HDFC Bank', currentRate: 8.3 },
  { name: 'ICICI Bank', currentRate: 8.4 },
  { name: 'SBI', currentRate: 8.5 },
  { name: 'Axis Bank', currentRate: 8.45 },
  { name: 'Kotak Mahindra', currentRate: 8.6 },
  { name: 'Bank of Baroda', currentRate: 8.55 },
];

export function generateMockAlerts(userId: string, loanId: string) {
  return [
    {
      id: '1',
      userId,
      loanId,
      alertType: 'rate_change' as const,
      title: 'Lower Interest Rates Available',
      message: 'HDFC cut rates to 8.3% - You\'re at 9%. Switch and save ₹2.1L',
      priority: 'high' as const,
      actionUrl: '/refinance',
      isRead: false,
      createdAt: new Date(),
    },
    {
      id: '2',
      userId,
      loanId,
      alertType: 'milestone' as const,
      title: '₹5L Principal Paid!',
      message: 'Congratulations! You just crossed ₹5L principal paid! 🎉',
      priority: 'medium' as const,
      isRead: false,
      createdAt: new Date(Date.now() - 86400000),
    },
    {
      id: '3',
      userId,
      alertType: 'streak' as const,
      title: 'Maintain Your Streak',
      message: 'Don\'t break your 8-month on-time streak! EMI due in 5 days.',
      priority: 'medium' as const,
      isRead: false,
      createdAt: new Date(Date.now() - 172800000),
    },
    {
      id: '4',
      userId,
      loanId,
      alertType: 'nudge' as const,
      title: 'Smart Spending Tip',
      message: 'You spent ₹18K on dining last month. ₹5K toward loan saves ₹3.2L in interest',
      priority: 'low' as const,
      isRead: true,
      createdAt: new Date(Date.now() - 259200000),
    },
  ];
}
